export const defaultData = {
  firstName: "Nodirbek",
  lastName: "Yunosov",
  badge: "Premium Graphic Designer",
  subtitle: "Grafik dizayner | 4 yillik tajriba | 1000+ loyiha",
  description:
    "Men bizneslar uchun sotuvga yo‘naltirilgan, zamonaviy va premium grafik dizaynlar yarataman. 4 yillik tajriba davomida 1000+ dan ortiq loyiha ustida ishlaganman.",
  telegram: "https://t.me/USERNAME",
  profile:
    "https://images.unsplash.com/photo-1547658719-da2b51169166?q=80&w=1200&auto=format&fit=crop",
  stat1: "4+",
  stat1Text: "Yil tajriba",
  stat2: "1000+",
  stat2Text: "Bajarilgan loyiha",
  stat3: "50+",
  stat3Text: "Doimiy mijoz",
  stat4: "100%",
  stat4Text: "Individual yondashuv",
  contactTitle: "Biznesingizni vizual kuchga aylantiramiz",
  contactText:
    "Logo, SMM post, packaging, banner yoki web dizayn kerak bo‘lsa, Telegram orqali bog‘laning.",
  services: [
    { title: "Logo dizayn", text: "Brend uchun esda qoladigan, toza va professional logotip yaratish." },
    { title: "SMM post dizayn", text: "Instagram, Telegram va reklama uchun sotuvga yo‘naltirilgan postlar." },
    { title: "Brending", text: "Rang, shrift, vizual uslub va brend ko‘rinishini yagona tizimga keltirish." },
    { title: "Packaging dizayn", text: "Mahsulot qadoqlari, qop dizaynlari, etiketka va premium maketlar." },
    { title: "Banner va reklama", text: "Outdoor, target, billboard va biznes reklamalari uchun kuchli dizaynlar." },
    { title: "Web dizayn UI", text: "Landing page, portfolio va biznes saytlar uchun zamonaviy interfeyslar." },
  ],
  works: [
    {
      id: "demo-1",
      title: "Logo dizayn",
      text: "Premium brend uchun minimal va kuchli logotip.",
      image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=1200&auto=format&fit=crop",
      imagePath: null,
      pdf: null,
      pdfPath: null,
    },
    {
      id: "demo-2",
      title: "SMM post",
      text: "Instagram reklama posti uchun sotuvga yo‘naltirilgan dizayn.",
      image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1200&auto=format&fit=crop",
      imagePath: null,
      pdf: null,
      pdfPath: null,
    },
    {
      id: "demo-3",
      title: "Packaging",
      text: "Mahsulot qadoqlash uchun zamonaviy dizayn.",
      image: "https://images.unsplash.com/photo-1607082350899-7e105aa886ae?q=80&w=1200&auto=format&fit=crop",
      imagePath: null,
      pdf: null,
      pdfPath: null,
    },
  ],
};
